# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_auto', '0025_conciliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='conciliada',
            field=models.IntegerField(choices=[(0, 'A Ser Conciliada'), (1, 'Conciliada')], default=0),
        ),
    ]
