# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0006_auto_20200123_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFormasPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_forma', models.IntegerField(verbose_name='Id da forma de pagamento')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('forma', models.CharField(max_length=200, verbose_name='Forma de pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PMesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_restaurante', models.IntegerField()),
                ('id_mesa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PPedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_mesa', models.IntegerField(verbose_name='N\xfamero da Mesa')),
                ('id_produto', models.IntegerField(verbose_name='Id do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PPedidosFormaPag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField(verbose_name='Id do Pedido')),
                ('mesa', models.IntegerField(default=0, verbose_name='Mesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('forma', models.CharField(max_length=200, verbose_name='Forma de pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_restaurante', models.IntegerField(verbose_name='Id do Restaurante')),
                ('id_prod', models.IntegerField(verbose_name='Id do Produto')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
