# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0008_auto_20200430_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_picpay',
            field=models.BooleanField(default=False),
        ),
    ]
