# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onshop_core', '0009_pedido_status_picpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_picpay',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='link_picpay',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
